import Head from "next/head";
import Menu from '../components/menu'
import Pinned from "../components/pinned";
import BlogList from "../components/blogList";
import Article from "../components/article";
import styles from "../styles/Home.module.css";
import { GraphQLClient, gql } from "graphql-request";

const clinet = new GraphQLClient(
  "https://api-ap-northeast-1.graphcms.com/v2/cl3r5o4vy8pmz01xi8szu1ly9/master"
);
const QUERY = gql`
  {
    posts {
      id
      title
      datePublished
      category
      description
      content {
        html
      }
      time
      author {
        name
        avatar {
          url
        }
      }
      coverImg {
        url
      }
    }
  }
`;

export async function getStaticProps() {
  const { posts } = await clinet.request(QUERY);
  return {
    props: {
      posts,     
    },
    revalidate:10
  };
}

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className="blog">
          <Menu/>
          <Pinned/>
          <BlogList posts={posts} />
          <Article/>
        </div>
      </div>
    </div>
  );
}
