import Head from "next/head";
import Menu from "../components/menu";
import Pinned from "../components/pinned";
import BlogList from "../components/blogList";
import Article from "../components/article";
import styles from "../styles/Home.module.css";
import { GraphQLClient, gql } from "graphql-request";

const clinet = new GraphQLClient(
  "https://api-ap-northeast-1.graphcms.com/v2/cl3r5o4vy8pmz01xi8szu1ly9/master"
);
const QUERY = gql`
  {
    posts {
      id
      title
      datePublished
      category
      description
      content {
        html
      }
      time
      author {
        name
        avatar {
          url
        }
      }
      coverImg {
        url
      }
    }
  }
`;

export async function getStaticProps() {
  const { posts } = await clinet.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function Home({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>我的博客系统</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="blog">
        <div className="blog-part is-menu">
          <a href="#" className="blog-menu">
            Work
            <svg
              fill="none"
              stroke="currentColor"
              strokeWidth=".7"
              strokeLinecap="round"
              strokeLinejoin="round"
              className="feather feather-arrow-up-right"
              viewBox="0 0 24 24"
            >
              <path d="M7 17L17 7M7 7h10v10" />
            </svg>
          </a>
          <a href="#" className="blog-menu">
            Studio
          </a>
          <a href="#" className="blog-menu">
            Blog
          </a>
          <a href="#" className="blog-menu">
            Contact
          </a>
          <a href="#" className="blog-menu mention">
            @MagazineDope
          </a>
          <a href="#" className="blog-menu subscribe">
            Subscribe
          </a>
        </div>
        <div className="blog-header blog-is-sticky">
          <div className="blog-article header-article">
            <div className="blog-big__title">Self</div>
            <div className="blog-menu rounded small-title">Pinned Issue</div>
          </div>
          <div className="blog-article page-number">NO. 01</div>
        </div>
        <div className="blog-header-container">
          {posts.map((post) => {
            return (
              <div className="blog-header" key={post.id}>
                <div className="blog-article header-article">
                  <div className="blog-big__title">{post.category}</div>
                  <div className="blog-menu small-title date">
                    {post.datePublished}
                  </div>
                </div>

                <div className="blog-article">
                  <img src={post.coverImg.url} alt="" />
                  <h2>{post.title}</h2>
                  <div className="blog-detail">
                    <span>By {post.author.name}</span>
                    <span>{post.time}</span>
                  </div>
                  <p>{post.description}</p>
                  <a href={'/posts/'+post.id}>
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      className="feather feather-corner-down-right"
                      viewBox="0 0 24 24"
                    >
                      <path d="M15 10l5 5-5 5" />
                      <path d="M4 4v7a4 4 0 004 4h12" />
                    </svg>
                    See More
                  </a>
                </div>
              </div>
            );
          })}
        </div>
        <div className="blog-part right-blog">
          <marquee width="100%" direction="left">
            <span>Now And Then You Miss It Sounds Make You Cry</span>
            <span>Now In - MoMa Sharing Exhibition NOW</span>
            <span>NYC Opens After Long Lockdown Check</span>
          </marquee>
          <div className="blog-right-title-container">
            <div className="blog-right-title">Featured Articles</div>
            <div className="blog-menu rounded">See All</div>
          </div>
          <div className="blog-right">
            <div className="blog-right-container">
              <div className="blog-title-date">
                <div className="blog-right-page">1</div>
                <div className="date">12.06.2021</div>
              </div>
              <div className="blog-right-page-title">
                Blonde - Widespread Acclaim
              </div>
              <div className="blog-right-page-subtitle">
                Blonde received widespread acclaim, with critics praising
                Ocean's introspective lyrics and the album's
              </div>
            </div>
            <div className="blog-right-container">
              <div className="blog-title-date">
                <div className="blog-right-page">2</div>
                <div className="date">12.06.2021</div>
              </div>
              <div className="blog-right-page-title">
                Introspective Lyrics and Beats
              </div>
              <div className="blog-right-page-subtitle">
                When we toured Scotland we stopped at several selft-sealing
                hpuses because hotels would
              </div>
            </div>
            <div className="blog-right-container">
              <div className="blog-title-date">
                <div className="blog-right-page">3</div>
                <div className="date">12.06.2021</div>
              </div>
              <div className="blog-right-page-title">
                The Language Of Gris: Comples Beauty Of Monochrome
              </div>
              <div className="blog-right-page-subtitle">
                The interior concept was conceived of by Dutch archtitect Studio
                Anne Holtrop who cleverly emulated
              </div>
            </div>
            <div className="blog-right-container">
              <div className="blog-title-date">
                <div className="blog-right-page">4</div>
                <div className="date">12.06.2021</div>
              </div>
              <div className="blog-right-page-title">
                A24 IS LAUNCHING ITS OWN BEAUTY BRAND
              </div>
              <div className="blog-right-page-subtitle">
                Blonde received widespread acclaim, with critics praising
                Ocean's introspective lyrics and the album's
              </div>
            </div>
            <div className="blog-right-container">
              <div className="blog-title-date">
                <div className="blog-right-page">5</div>
                <div className="date">12.06.2021</div>
              </div>
              <div className="blog-right-page-title">
                Elon Musk's SpaceX is launching a moon satellite
              </div>
              <div className="blog-right-page-subtitle">
                The interior concept was conceived of by Dutch archtitect Studio
                Anne Holtrop who cleverly emulated
              </div>
            </div>
            <div className="blog-right-container">
              <div className="blog-title-date">
                <div className="blog-right-page">6</div>
                <div className="date">12.06.2021</div>
              </div>
              <div className="blog-right-page-title">
                What Happens When You Leave Your Old life Behind
              </div>
              <div className="blog-right-page-subtitle">
                The interior concept was conceived of by Dutch archtitect Studio
                Anne Holtrop who cleverly emulated
              </div>
            </div>
            <div className="circle">
              <div className="circle-title">Leave Your Old Life Behind</div>
              <div className="circle-subtitle">
                Don't try to be like someone else, be yourself. Be secure with
                yourself.
              </div>
              <div className="circle-footer">Explore</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
